name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./

env:
  MAVEN_OPTS: -Xmx2g -XX:+UseContainerSupport

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Build & run tests
        run: mvn -B verify --fail-at-end

  static-code-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Install modules (skip tests)
        run: mvn -B install -DskipTests

      - name: Static code analysis
        run: mvn checkstyle:check pmd:check spotbugs:check

      - name: Upload analysis reports
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-reports
          path: |
            */target/site/checkstyle.html
            */target/site/pmd.html
            */target/spotbugsXml.xml

  upload-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Generate and publish coverage
        run: mvn -B verify 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          slug: h00dieB0y/tika-service

  sonar-analysis:
    name: SonarQube / SonarCloud
    needs: upload-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN:       ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL:    https://sonarcloud.io
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }} # only for SonarCloud
        run: |
          mvn --batch-mode sonar:sonar \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            $( [ -n "$SONAR_HOST_URL" ]    && echo "-Dsonar.host.url=$SONAR_HOST_URL" ) \
            $( [ -n "$SONAR_ORGANIZATION" ] && echo "-Dsonar.organization=$SONAR_ORGANIZATION" )
