name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# cancel redundant runs on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# apply to all run steps
defaults:
  run:
    shell: bash
    working-directory: ./

env:
  MAVEN_OPTS: -Xmx2g -XX:+UseContainerSupport

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Build & run tests
        run: mvn -B verify --fail-at-end

  static-code-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Install modules (skip tests)
        run: mvn -B install -DskipTests

      - name: Static code analysis
        run: mvn checkstyle:check pmd:check spotbugs:check

      - name: Upload analysis reports
        uses: actions/upload-artifact@v3
        with:
          name: code-analysis-reports
          path: |
            */target/site/checkstyle.html
            */target/site/pmd.html
            */target/spotbugsXml.xml

  upload-coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
